services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backstage:
    build:
      context: ./backstage
    container_name: backstage
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DATABASE: backstage
    ports:
      - "7000:7000"
    depends_on:
      - postgres

volumes:
  postgres_data:
